### PR TITLE
Optimize server parameters, refactor with env file

### PR DESCRIPTION
**Pull request by pasqualedevita**
### Motivation and context

restore options from https://docs.microsoft.com/it-it/azure/postgresql/howto-migrate-using-dump-and-restore#for-the-restore

### Type of changes

- [ ] Add new resources
- [x] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [x] No

### Other information

---

### CODE REVIEW

**Comment by pasqualedevita** [comment]
@GiovanniMancini do we want to try to change also restore command as follow?

`nohup pg_restore -h "${db_host}" -p 5432 -U "${db_user}" -j 8 -d "${db_backup}" "${dump_dir}/${db_backup}" -v 2>&1 | tee "${log_dir}/${db_backup}_data.out"`

**Comment by GiovanniMancini** [comment]
> @GiovanniMancini do we want to try to change also restore command as follow?
> 
> `nohup pg_restore -h "${db_host}" -p 5432 -U "${db_user}" -j 8 -d "${db_backup}" "${dump_dir}/${db_backup}" -v 2>&1 | tee "${log_dir}/${db_backup}_data.out"`



> @GiovanniMancini do we want to try to change also restore command as follow?
> 
> `nohup pg_restore -h "${db_host}" -p 5432 -U "${db_user}" -j 8 -d "${db_backup}" "${dump_dir}/${db_backup}" -v 2>&1 | tee "${log_dir}/${db_backup}_data.out"`

@pasqualedevita usually `nohup` is used on the same command where you use the ampersand `&`. So we have two alternatives: 1. launching the restore script as `nohup bash restore_script.sh &` 2. or putting `nohup pg_restore ... &` _inside_ the restore script. The second alternatives improves parallelism, as you can restore different db in parallel, but destroys the timeline file

**Comment by pasqualedevita** [comment]
Vote for `nohup bash restore_script.sh &`

**Comment by GiovanniMancini** [comment]
> Vote for `nohup bash restore_script.sh env &`

Since the `rtd` and `fa` databases are small, I agree

**Pull request merged**
