### PR TITLE
feat: Added payments admin as codeowner

### PR DESCRIPTION
**Pull request by mamari90**
### Motivation and context

The cloud payments team ( @mamari90 @diegolagospagopa @re-sh-cloud-arch ) needs to be able to approve PRs on this repo for daily work

@gammam @AlessioCarpitelli 

### Type of changes

- [ ] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

#### Has This Been Tested?

- [ ] Yes
- [ ] No

### Other information
Target: 
```

```

#### How Has This Been Tested?

- [ ] Unit Test Suite
- [ ] Integration Test Suite
- [ ] Api Tests
- [ ] Load Tests

[Link to test results](https://pagopa.atlassian.net/browse/RTD-XXXX)

---

### CODE REVIEW

**Comment by gammam** [comment]
@mamari90 any diff with @pagopa/infrastructure-admins ? 
if I understood well 
- @pagopa/payments-cloud-admin are cloud engineers from Payment Area
- @pagopa/infrastructure-admins are cloud engineers from Engineering Area 

in that case @pagopa/infrastructure-admins should be removed, in case of emergency they can apply on infrastructure as admin using cli or azure portal.

**Comment by mamari90** [comment]
@gammam infrastructure-admins has been removed. That team will probably be deleted in the future

**Comment by gammam** [comment]
@mamari90 infrastructer-admins seems to be not deleted , is it correct ?

**Comment by mamari90** [comment]
@gammam sorry, now it's removed. it was done on the wrong branch

**Review by gammam — APPROVED** [review]

**Pull request merged**
