### PR TITLE
[RTD-349] Add new role assignment for data contributor on SFTP to APIM

### PR DESCRIPTION
**Pull request by TommasoLencioni**
This PR proposes to grant write permission to the APIM to SFTP.
### List of changes
- add new role assignment

### Type of changes

- [x] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [x] No

### Other information

---

### CODE REVIEW

**Comment by GiovanniMancini** [comment]
@TommasoLencioni Is this still in draft?

**Comment by TommasoLencioni** [comment]
> @TommasoLencioni Is this still in draft?
Yes, the static analysis fails.
The added code should refactored and applied.

**Comment by TommasoLencioni** [comment]
@GiovanniMancini now it should be ready!

**Comment by GiovanniMancini** [comment]
@TommasoLencioni could you please run a pre-commit check?

**Comment by TommasoLencioni** [comment]
> @TommasoLencioni could you please run a pre-commit check?

Done

**Comment by GiovanniMancini** [comment]
@TommasoLencioni please note that proposed changes impact prod environment too

**Pull request merged**
