### PR TITLE
feat: IDP-1244_rimozione_indice_onboarding_citizen

### PR DESCRIPTION
**Pull request by sbellezz**
### Type of changes

- [ ] Add new resources
- [x] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [x] No

#### Has This Been Tested?

- [x] Yes
- [ ] No

### Other information
Target: 
```

```

#### How Has This Been Tested?

- [ ] Unit Test Suite
- [ ] Integration Test Suite
- [x] Api Tests
- [ ] Load Tests

[Link to test results](https://pagopa.atlassian.net/browse/RTD-XXXX)

---

### CODE REVIEW

**Review by GiovanniMancini — CHANGES_REQUESTED** [review]
As far as I can understand, this demands emptying the collection

**Comment by sbellezz** [comment]
@GiovanniMancini It's not a problem: we could either emptying the collection or to bonify it.
In dev we are bonifying it (probably we will do the same process in uat)

**Comment by GiovanniMancini** [comment]
> @GiovanniMancini It's not a problem: we could either emptying the collection or to bonify it. In dev we are bonifying it (probably we will do the same process in uat)

@sbellezz  Do you want me to wait till the collection is empty, or can I apply the changes?

**Comment by sbellezz** [comment]
@GiovanniMancini we should wait to apply it because this afternoon there is a meeting on the performance onboarding

**Pull request merged**
