### PR TITLE
Scale down postgresql UAT

### PR DESCRIPTION
**Pull request by pasqualedevita**
### List of changes

scale down postgresql uat from `GP_Gen5_8` to `GP_Gen5_4`

### Motivation and context

cost saving

### Type of changes

- [ ] Add new resources
- [x] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [x] No

### Other information

---

### CODE REVIEW

**Comment by pasqualedevita** [comment]
@GiovanniMancini can we scale down to `GP_Gen5_2`?

**Comment by pasqualedevita** [comment]
due connection limits we need to scale down microservices, now we have 347 active connections

GP_Gen5_2 = 145
GP_Gen5_4 = 245
GP_Gen5_8 = 475

ref. https://docs.microsoft.com/it-it/azure/postgresql/concepts-limits

**Comment by ElfoLiNk** [comment]
@pasqualedevita you should change also the alerts threshold 

```
  # https://docs.microsoft.com/it-it/azure/postgresql/concepts-limits
  # GP_Gen5_2 -| 145 / 100 * 80 = 116
  # GP_Gen5_8 -| 475 / 100 * 80 = 380
  # GP_Gen5_32 -| 1495 / 100 * 80 = 1196
  max_active_connections = {
    aggregation = "Average"
    metric_name = "active_connections"
    operator    = "GreaterThan"
    threshold   = 380
    frequency   = "PT5M"
    window_size = "PT5M"
    dimension   = []
  }
```

**Comment by GiovanniMancini** [comment]
> due connection limits we need to scale down microservices, now we have 347 active connections
> 
> GP_Gen5_2 = 145 GP_Gen5_4 = 245 GP_Gen5_8 = 475
> 
> ref. https://docs.microsoft.com/it-it/azure/postgresql/concepts-limits

In principle UAT can be scaled down (both microservices and DB) to `dev` like settings, the only problem is when we do load tests

**Comment by pasqualedevita** [comment]
> @pasqualedevita you should change also the alerts threshold
> 
> ```
>   # https://docs.microsoft.com/it-it/azure/postgresql/concepts-limits
>   # GP_Gen5_2 -| 145 / 100 * 80 = 116
>   # GP_Gen5_8 -| 475 / 100 * 80 = 380
>   # GP_Gen5_32 -| 1495 / 100 * 80 = 1196
>   max_active_connections = {
>     aggregation = "Average"
>     metric_name = "active_connections"
>     operator    = "GreaterThan"
>     threshold   = 380
>     frequency   = "PT5M"
>     window_size = "PT5M"
>     dimension   = []
>   }
> ```

thank u Matteo :) now alerts are disabled in uat but It's correct to update the value

**Comment by pasqualedevita** [comment]
> > due connection limits we need to scale down microservices, now we have 347 active connections
> > GP_Gen5_2 = 145 GP_Gen5_4 = 245 GP_Gen5_8 = 475
> > ref. https://docs.microsoft.com/it-it/azure/postgresql/concepts-limits
> 
> In principle UAT can be scaled down (both microservices and DB) to `dev` like settings, the only problem is when we do load tests

When will need to do load test, we'll scale up :)
PS: I scaled down bpdmscitizen from 4 to 1 replica and now active connections are 222

**Pull request merged**
