### PR TITLE
feat: [IDP-1142] update swagger io for payment exceptions

### PR DESCRIPTION
**Pull request by giulia-tremolada**
### Type of changes

- [ ] Add new resources
- [x] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [x] No

#### Has This Been Tested?

- [x] Yes
- [ ] No

### Other information
Target: 
```

```

#### How Has This Been Tested?

- [ ] Unit Test Suite
- [ ] Integration Test Suite
- [x] Api Tests
- [ ] Load Tests

[Link to test results](https://pagopa.atlassian.net/browse/RTD-XXXX)

---

### CODE REVIEW

**Review by gammam — CHANGES_REQUESTED** [review]
TransactionErrorDTO shall : 
- indicate witch message to show to the user ( UI Screen ) -> `code`
- describes the reason of the error ( useful for debug )  -> `description`

`code` could be  without explicit meaning like "IDPAY_100" or with a generic name ( not related to the function) like "IDPAY_AUTH_NEG"

Each Enum shall be map on only one UI Screen on [Figma](https://www.figma.com/file/SuYjyjZlieQqRS8n1B6qbF/Flussi-App-ID-Pay?type=design&node-id=7170-32185&t=ezSLa2pAGH7kiQTk-0)

**Review by mastro993 — APPROVED** [review]

**Comment by GiovanniMancini** [comment]
> TransactionErrorDTO shall :
> 
> * indicate witch message to show to the user ( UI Screen ) -> `code`
> * describes the reason of the error ( useful for debug )  -> `description`
> 
> `code` could be without explicit meaning like "IDPAY_100" or with a generic name ( not related to the function) like "IDPAY_AUTH_NEG"
> 
> Each Enum shall be map on only one UI Screen on [Figma](https://www.figma.com/file/SuYjyjZlieQqRS8n1B6qbF/Flussi-App-ID-Pay?type=design&node-id=7170-32185&t=ezSLa2pAGH7kiQTk-0)

@gammam As far as I can understand, this PR fixes the issue of having exceptions encoded with an HTTP status of 200. @frtrinca, can you confirm? 
If this PR gets merged, each exception - as you are requesting - will have
- an HTTP status that clients associate with anomalies (e.g. 400, 403, and so on),
- a code represented by an enum value,
- a message for debugging purposes.
App IO can easily map returned codes with its screens. @mastro993, Do you agree? So I suggest merging this PR and eventually changing the mapping in a different task

**Review by GiovanniMancini — APPROVED** [review]

**Comment by mastro993** [comment]
> > TransactionErrorDTO shall :
> > 
> > * indicate witch message to show to the user ( UI Screen ) -> `code`
> > * describes the reason of the error ( useful for debug )  -> `description`
> > 
> > `code` could be without explicit meaning like "IDPAY_100" or with a generic name ( not related to the function) like "IDPAY_AUTH_NEG"
> > Each Enum shall be map on only one UI Screen on [Figma](https://www.figma.com/file/SuYjyjZlieQqRS8n1B6qbF/Flussi-App-ID-Pay?type=design&node-id=7170-32185&t=ezSLa2pAGH7kiQTk-0)
> 
> @gammam As far as I can understand, this PR fixes the issue of having exceptions encoded with an HTTP status of 200. @frtrinca, can you confirm? If this PR gets merged, each exception - as you are requesting - will have
> 
> * an HTTP status that clients associate with anomalies (e.g. 400, 403, and so on),
> * a code represented by an enum value,
> * a message for debugging purposes.
> 
> App IO can easily map returned codes with its screens. @mastro993, Do you agree? So I suggest merging this PR and changing the mapping in a different task

I agree. In this way our screen mapping is easier!

**Review by gammam — APPROVED** [review]
Ok, we change the Enum values later

**Pull request merged**
